version: '3'

services:
    database:
        build: ./mysql_data
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'gamabank'
        ports:
            - '3306:3306'
        volumes:
            - ./mysql_volumes:/var/lib/mysql
        restart: always

    adminer:
        image: adminer
        ports:
            - 8080:8080

