version: "3"

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - ./pg-volume/:/var/lib/postgresql/data

  app:
    build: .
    command: npm run start:dev
    depends_on: 
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    
