version: "3"

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '15432:5432'
    volumes:
      - ./pg-volume/:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "diogoagrasmsdc@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2021!"
    ports:
      - "16543:80"
    depends_on:
      - database

  app:
    build: .
    command: npm run start:dev
    depends_on: 
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    
